CREATE PROC XEM_CTVT
AS
BEGIN
SELECT* FROM Chi_Tiet_Vat_Tu
END 

CREATE PROC THEM_CTVT(
@MA_HANG NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
IF @MA_PB IN (SELECT maPB FROM PhongBan)
   INSERT INTO DuAn(tenDA, diaDiem,ngayBatDau,ngayKetThuc, maPB) VALUES (@TEN_DA,@DIA_DIEM,@NGAY_BD,@NGAY_KT,@MA_PB)
IF @MA_PB NOT IN (SELECT maPB FROM PhongBan)
   INSERT INTO PhongBan(maPB) VALUES(@MA_PB)
END