CREATE PROC XEM_CTVT
AS
BEGIN
SELECT* FROM Chi_Tiet_Vat_Tu
END 

CREATE PROC THEM_CTVT(
@MA_HANG NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
IF @MA_PB IN (SELECT maPB FROM PhongBan)
   INSERT INTO DuAn(tenDA, diaDiem,ngayBatDau,ngayKetThuc, maPB) VALUES (@TEN_DA,@DIA_DIEM,@NGAY_BD,@NGAY_KT,@MA_PB)
IF @MA_PB NOT IN (SELECT maPB FROM PhongBan)
   INSERT INTO PhongBan(maPB) VALUES(@MA_PB)
END

CREATE PROC THEM_CTVT(
@MA_HANG INT,
@MA_PN INT,
@MA_PX INT,
@NGAY DATETIME,
@LUONG_NHAP INT,
@LUONG_XUAT INT,
@TON_DK INT
)
AS
BEGIN
IF @MA_PN IN(SELECT MA_PN FROM Phieu_Nhap) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
       INSERT INTO Chi_Tiet_Vat_Tu(MA_HANG,MA_PX,MA_PN,NGAY,LUONG_NHAP,LUONG_XUAT,TON_DK) VALUES (@MA_HANG,@MA_PX,@MA_PN,@NGAY,@LUONG_NHAP,@LUONG_XUAT,@TON_DK)
IF @MA_PX IN(SELECT MA_PX FROM Phieu_Xuat) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
       INSERT INTO Chi_Tiet_Vat_Tu(MA_HANG,MA_PX,MA_PN,NGAY,LUONG_NHAP,LUONG_XUAT,TON_DK) VALUES (@MA_HANG,@MA_PX,@MA_PN,@NGAY,@LUONG_NHAP,@LUONG_XUAT,@TON_DK)
END
THEM_CTVT(1,12,12,'4-5-2017',21,21,21)

CREATE PROC SUA_CTVT(
@MA_HANG INT,
@MA_PN INT,
@MA_PX INT,
@NGAY DATETIME,
@LUONG_NHAP INT,
@LUONG_XUAT INT,
@TON_DK INT
)
AS
BEGIN
IF @MA_PN IN(SELECT MA_PN FROM Phieu_Nhap) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
        UPDATE Chi_Tiet_Vat_Tu SET MA_HANG=@MA_HANG,MA_PX=@MA_PX,MA_PN=@MA_PN,NGAY=@NGAY,LUONG_NHAP=@LUONG_NHAP,LUONG_XUAT=@LUONG_XUAT,TON_DK=@TON_DK
IF @MA_PX IN(SELECT MA_PX FROM Phieu_Xuat) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
        UPDATE Chi_Tiet_Vat_Tu SET MA_HANG=@MA_HANG,MA_PX=@MA_PX,MA_PN=@MA_PN,NGAY=@NGAY,LUONG_NHAP=@LUONG_NHAP,LUONG_XUAT=@LUONG_XUAT,TON_DK=@TON_DK
END

CREATE PROC XOA_CTVT(
@MA_HANG INT,
@MA_PX INT,
@MA_PN INT
)
AS
BEGIN
IF @MA_PN IN(SELECT MA_PN FROM Phieu_Nhap) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
      DELETE FROM Chi_Tiet_Vat_Tu WHERE MA_HANG=@MA_HANG AND MA_PN=@MA_PN
IF @MA_PX IN(SELECT MA_PX FROM Phieu_Xuat) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
       DELETE FROM Chi_Tiet_Vat_Tu WHERE MA_HANG=@MA_HANG AND MA_PX=@MA_PX
      
END

CREATE PROC THEM_HANG_HOA(
@MA_HANG INT,
@TEN_HANG NVARCHAR(50),
@MA_NUOC_SX INT,
@KICH_THUOC NVARCHAR(50),
@MA_LOAI_HANG INT,
@DON_VI_TINH NVARCHAR(50),
@LUONG_TON INT,
@MA_KHO INT
)
AS
BEGIN
IF(@MA_NUOC_SX IN(SELECT MA_NUOC_SX FROM Nuoc_SX) AND @MA_LOAI_HANG IN(SELECT MA_LOAI_HANG FROM Loai_Hang) AND @MA_KHO IN(SELECT MA_KHO FROM Danh_Muc_Kho))
     INSERT INTO Danh_Muc_Hang_Hoa(TEN_HANG,MA_NUOC_SX,KICH_THUOC,MA_LOAI_HANG,DON_VI_TINH,LUONG_TON,MA_KHO) VALUES(@TEN_HANG,@MA_NUOC_SX,@KICH_THUOC,@MA_LOAI_HANG,@DON_VI_TINH,@LUONG_TON,@MA_KHO)
END

CREATE PROC SUA_HANG_HOA(
@MA_HANG INT,
@TEN_HANG NVARCHAR(50),
@MA_NUOC_SX INT,
@KICH_THUOC NVARCHAR(50),
@MA_LOAI_HANG INT,
@DON_VI_TINH NVARCHAR(50),
@LUONG_TON INT,
@MA_KHO INT
)
AS
BEGIN
IF(@MA_NUOC_SX IN(SELECT MA_NUOC_SX FROM Nuoc_SX) AND @MA_LOAI_HANG IN(SELECT MA_LOAI_HANG FROM Loai_Hang) AND @MA_KHO IN(SELECT MA_KHO FROM Danh_Muc_Kho))
     UPDATE Danh_Muc_Hang_Hoa SET TEN_HANG=@TEN_HANG,MA_NUOC_SX=@MA_NUOC_SX,KICH_THUOC=@KICH_THUOC,MA_LOAI_HANG=@MA_LOAI_HANG,DON_VI_TINH=@DON_VI_TINH,LUONG_TON=@LUONG_TON,MA_KHO=@MA_KHO
END

CREATE PROC XOA_HANG_HOA(
@MA_HANG INT
)
AS
BEGIN
IF @MA_HANG IN(SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
      DELETE FROM Danh_Muc_Hang_Hoa WHERE MA_HANG=@MA_HANG 

END

CREATE PROC THEM_KH(
@MA_KH INT,
@TEN_KH NVARCHAR(50),
@DIA_CHI NVARCHAR(50),
@SDT NVARCHAR(50)
)
