CREATE PROC XEM_CTVT
AS
BEGIN
SELECT* FROM Chi_Tiet_Vat_Tu
END 

CREATE PROC THEM_CTVT(
@MA_HANG NVARCHAR(100),
@DIA_DIEM NVARCHAR(100),
@NGAY_BD DATETIME,
@NGAY_KT DATETIME,
@MA_PB INT
)
AS
BEGIN
IF @MA_PB IN (SELECT maPB FROM PhongBan)
   INSERT INTO DuAn(tenDA, diaDiem,ngayBatDau,ngayKetThuc, maPB) VALUES (@TEN_DA,@DIA_DIEM,@NGAY_BD,@NGAY_KT,@MA_PB)
IF @MA_PB NOT IN (SELECT maPB FROM PhongBan)
   INSERT INTO PhongBan(maPB) VALUES(@MA_PB)
END

CREATE PROC THEM_CTVT(
@MA_HANG INT,
@MA_PN INT,
@MA_PX INT,
@NGAY DATETIME,
@LUONG_NHAP INT,
@LUONG_XUAT INT,
@TON_DK INT
)
AS
BEGIN
IF @MA_PN IN(SELECT MA_PN FROM Phieu_Nhap) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
       INSERT INTO Chi_Tiet_Vat_Tu(MA_HANG,MA_PX,MA_PN,NGAY,LUONG_NHAP,LUONG_XUAT,TON_DK) VALUES (@MA_HANG,@MA_PX,@MA_PN,@NGAY,@LUONG_NHAP,@LUONG_XUAT,@TON_DK)
IF @MA_PX IN(SELECT MA_PX FROM Phieu_Xuat) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
       INSERT INTO Chi_Tiet_Vat_Tu(MA_HANG,MA_PX,MA_PN,NGAY,LUONG_NHAP,LUONG_XUAT,TON_DK) VALUES (@MA_HANG,@MA_PX,@MA_PN,@NGAY,@LUONG_NHAP,@LUONG_XUAT,@TON_DK)
END
THEM_CTVT 7,3,2,'4-5-2017',21,21,21

CREATE PROC SUA_CTVT(
@MA_HANG INT,
@MA_PN INT,
@MA_PX INT,
@NGAY DATETIME,
@LUONG_NHAP INT,
@LUONG_XUAT INT,
@TON_DK INT
)
AS
BEGIN
IF @MA_PN IN(SELECT MA_PN FROM Phieu_Nhap) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
        UPDATE Chi_Tiet_Vat_Tu SET MA_HANG=@MA_HANG,MA_PX=@MA_PX,MA_PN=@MA_PN,NGAY=@NGAY,LUONG_NHAP=@LUONG_NHAP,LUONG_XUAT=@LUONG_XUAT,TON_DK=@TON_DK
IF @MA_PX IN(SELECT MA_PX FROM Phieu_Xuat) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
        UPDATE Chi_Tiet_Vat_Tu SET MA_HANG=@MA_HANG,MA_PX=@MA_PX,MA_PN=@MA_PN,NGAY=@NGAY,LUONG_NHAP=@LUONG_NHAP,LUONG_XUAT=@LUONG_XUAT,TON_DK=@TON_DK
END

CREATE PROC XOA_CTVT(
@MA_HANG INT,
@MA_PX INT,
@MA_PN INT
)
AS
BEGIN
IF @MA_PN IN(SELECT MA_PN FROM Phieu_Nhap) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
      DELETE FROM Chi_Tiet_Vat_Tu WHERE MA_HANG=@MA_HANG AND MA_PN=@MA_PN
IF @MA_PX IN(SELECT MA_PX FROM Phieu_Xuat) AND @MA_HANG IN (SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
       DELETE FROM Chi_Tiet_Vat_Tu WHERE MA_HANG=@MA_HANG AND MA_PX=@MA_PX
      
END

CREATE PROC XEM_HANG_HOA
AS
BEGIN
SELECT * FROM Danh_Muc_Hang_Hoa
END

CREATE PROC THEM_HANG_HOA(
@TEN_HANG NVARCHAR(50),
@MA_NUOC_SX INT,
@KICH_THUOC NVARCHAR(50),
@MA_LOAI_HANG INT,
@DON_VI_TINH NVARCHAR(50),
@LUONG_TON INT,
@MA_KHO INT
)
AS
BEGIN
IF(@MA_NUOC_SX IN(SELECT MA_NUOC_SX FROM Nuoc_SX) AND @MA_LOAI_HANG IN(SELECT MA_LOAI_HANG FROM Loai_Hang) AND @MA_KHO IN(SELECT MA_KHO FROM Danh_Muc_Kho))
     INSERT INTO Danh_Muc_Hang_Hoa(TEN_HANG,MA_NUOC_SX,KICH_THUOC,MA_LOAI_HANG,DON_VI_TINH,LUONG_TON,MA_KHO) VALUES(@TEN_HANG,@MA_NUOC_SX,@KICH_THUOC,@MA_LOAI_HANG,@DON_VI_TINH,@LUONG_TON,@MA_KHO)
END

CREATE PROC SUA_HANG_HOA(
@MA_HANG INT,
@TEN_HANG NVARCHAR(50),
@MA_NUOC_SX INT,
@KICH_THUOC NVARCHAR(50),
@MA_LOAI_HANG INT,
@DON_VI_TINH NVARCHAR(50),
@LUONG_TON INT,
@MA_KHO INT
)
AS
BEGIN
IF(@MA_NUOC_SX IN(SELECT MA_NUOC_SX FROM Nuoc_SX) AND @MA_LOAI_HANG IN(SELECT MA_LOAI_HANG FROM Loai_Hang) AND @MA_KHO IN(SELECT MA_KHO FROM Danh_Muc_Kho))
     UPDATE Danh_Muc_Hang_Hoa SET TEN_HANG=@TEN_HANG,MA_NUOC_SX=@MA_NUOC_SX,KICH_THUOC=@KICH_THUOC,MA_LOAI_HANG=@MA_LOAI_HANG,DON_VI_TINH=@DON_VI_TINH,LUONG_TON=@LUONG_TON,MA_KHO=@MA_KHO WHERE MA_HANG=@MA_HANG
END

CREATE PROC XOA_HANG_HOA(
@MA_HANG INT
)
AS
BEGIN
IF @MA_HANG IN(SELECT MA_HANG FROM Danh_Muc_Hang_Hoa)
      DELETE FROM Chi_Tiet_Phieu_Nhap WHERE MA_HANG=@MA_HANG 
	  DELETE FROM Chi_Tiet_Phieu_Xuat WHERE MA_HANG=@MA_HANG 
      DELETE FROM Danh_Muc_Hang_Hoa WHERE MA_HANG=@MA_HANG 

END

CREATE PROC THEM_KH(
@TEN_KH NVARCHAR(50),
@DIA_CHI NVARCHAR(50),
@DIEN_THOAI NVARCHAR(50)
)
AS
BEGIN
INSERT INTO Khach_Hang(TEN_KH,DIA_CHI,DIEN_THOAI) VALUES (@TEN_KH,@DIA_CHI,@DIEN_THOAI)
END

CREATE PROC SUA_KH(
@MA_KH INT,
@TEN_KH NVARCHAR(50),
@DIA_CHI NVARCHAR(50),
@DIEN_THOAI NVARCHAR(50)
)
AS
BEGIN
UPDATE Khach_Hang SET TEN_KH=@TEN_KH,DIA_CHI=@DIA_CHI,DIEN_THOAI=@DIEN_THOAI WHERE MA_KH=@MA_KH
END


CREATE PROC XEM_KH
AS
BEGIN
SELECT * FROM Khach_Hang
END

CREATE PROC XOA_KH(
@MA_KH INT
)
AS
BEGIN
 DELETE FROM Khach_Hang WHERE MA_KH=@MA_KH  
END

CREATE PROC THEM_LOAI_HANG(
@LOAI_HANG NVARCHAR(50)
)
AS
BEGIN
INSERT INTO Loai_Hang(LOAI_HANG) VALUES(@LOAI_HANG)
END

CREATE PROC XEM_LOAI_HANG
AS
BEGIN
SELECT * FROM Loai_Hang
END

CREATE PROC SUA_LOAI_HANG(
@MA_LOAI_HANG INT,
@LOAI_HANG NVARCHAR(50)
)
AS
BEGIN
UPDATE Loai_Hang SET LOAI_HANG=@LOAI_HANG WHERE MA_LOAI_HANG=@MA_LOAI_HANG
END

CREATE PROC XOA_LOAI_HANG(
@MA_LOAI_HANG INT
)
AS
BEGIN
DELETE Loai_Hang WHERE MA_LOAI_HANG=@MA_LOAI_HANG
END

CREATE PROC XEM_KHO
AS
BEGIN
SELECT *FROM Danh_Muc_Kho
END

CREATE PROC THEM_KHO(
@TEN_KHO NVARCHAR(50),
@DIA_CHI NVARCHAR(50),
@SDT NVARCHAR(50),
@TEN_THU_KHO NVARCHAR(50)
)
AS
BEGIN
INSERT INTO Danh_Muc_Kho(TEN_KHO,DIA_CHI,DIEN_THOAI,TEN_THU_KHO) VALUES(@TEN_KHO,@DIA_CHI,@SDT,@TEN_THU_KHO)
END

CREATE PROC SUA_KHO(
@MA_KHO INT,
@TEN_KHO NVARCHAR(50),
@DIA_CHI NVARCHAR(50),
@SDT NVARCHAR(50),
@TEN_THU_KHO NVARCHAR(50)
)
AS
BEGIN
UPDATE Danh_Muc_Kho SET TEN_KHO=@TEN_KHO, DIA_CHI=@DIA_CHI,DIEN_THOAI=@SDT,TEN_THU_KHO=@TEN_THU_KHO WHERE MA_KHO=@MA_KHO
END

CREATE PROC XOA_KHO(
@MA_KHO INT
)
AS
BEGIN
DELETE Danh_Muc_Kho WHERE MA_KHO=@MA_KHO
END